# Generated by Django 2.1.4 on 2019-01-07 04:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bots',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('build_id', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('longit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LogsMovements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ist_id', models.CharField(max_length=10)),
                ('build_id', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.CharField(max_length=255)),
                ('build_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('ist_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('build_id', models.CharField(max_length=255)),
                ('range_user', models.IntegerField()),
                ('lat', models.FloatField()),
                ('longit', models.FloatField()),
            ],
        ),
    ]
