"""
Django settings for MessagesDisseminationWebApp project.
Generated by 'django-admin startproject' using Django 2.1.4.
For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'j@v#6c9!-&qx_h-w#^)!!+04%1sg4zv+^u6yd=r17vyv6)-we+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

LOGIN_URL = '/admin/login/'

LOGIN_REDIRECT_URL = '/admin/'


# Application definition

INSTALLED_APPS = [
    'users.apps.UsersConfig',
    'admin.apps.AdminConfig',
    'management.apps.ManagementConfig', 
    #'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MessagesDisseminationWebApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MessagesDisseminationWebApp.wsgi.application'

redirect_uri = ''
# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
if os.getenv('GAE_APPLICATION', None):
    redirect_uri += 'https://asint-227820.appspot.com/app/auth/'
    client_id ='1695915081465930'
    secret= 'XXknAbAk2nTLFdYByKqjDXVC+k94NYc5t34EUGYAxD4qaWUB+aopdY2z/9j5oRvDoTJFpaHhg42dsQ+mf6Gesg=='
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'HOST': '/cloudsql/asint-227820:europe-west1:sqlinstance',
            'USER': 'sqluser',
            'PASSWORD': 'sqluser',
            'NAME': 'instanceBD',
        }
    }

else:
    redirect_uri += 'http://127.0.0.1:8000/app/auth/'
    client_id = '1977390058176584'
    secret = 'PnHgsbWQclqX5fNUXNzyN2JFfI8hnb1XqWVqjXm7vhycVeuatuYbSJN+iKKzeKLbIuAik0v1zxDMt87zr0YLVQ=='
    #DATABASES = {
        #'default': {
           # 'ENGINE': 'django.db.backends.mysql',
          #  'HOST': '127.0.0.1',
         #   'PORT': '3306',
        #    'NAME': 'instanceBD',
       #     'USER': 'sqluser',
      #      'PASSWORD': 'sqluser',
     #   }
    #}
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),

        }
    }


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]





# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'static'

if os.getenv('GAE_APPLICATION', None):
    
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': '85.242.177.164:12345',
        }
    }

else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
            'KEY_PREFIX': 'myapp',
            'LOCATION': '127.0.0.1:11211',
        }
    }